config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'messages#index'

  resources :messages, only: %i[create show new index]
  resources :inboxes, only: [:show]

  resources :prescriptions, only: %i[show create new index]

  resources :patients, only: [] do
    get :dashboard

    member do
      post :lost_script
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  # Associations
  belongs_to :inbox
  belongs_to :outbox
  belongs_to :prescription, optional: true
  belongs_to :replied_with_message, class_name: 'Message', foreign_key: 'replied_to', optional: true
  belongs_to :replied_for, class_name: 'Message', foreign_key: 'reply_to_id', optional: true

  # Validations
  validates :body, presence: true, length: { maximum: 500 }

  after_create :update_inbox_and_outbox_count
  after_update :update_unread_count_on_read
  after_destroy :decrement_unread_count_if_necessary

  scope :unread, -> { where(read: false) }

  class << self
    def notify_admin_of_prescription_request(user, admin, body, prescription_id)
      message = new( # Create a Message object here
        body:,
        outbox: user.outbox,
        inbox: admin.inbox,
        prescription_id:
      )
      create_with_transaction(message)
    end

    def create_message(params)
      create_with_transaction(new(params))
    end

    def create_reply(params)
      message = prepare_reply_params(params)

      create_with_transaction(message) do |saved_message|
        update_replied_message(saved_message.reply_to_id, saved_message.id)
      end
    end

    def determine_recipient_inbox(reply_message_id)
      return User.default_doctor.inbox unless reply_message_id

      old_message = find_by(id: reply_message_id)
      return old_message.inbox unless old_message.inbox.user.is_patient?

      old_message.created_at > 7.days.ago ? User.default_doctor.inbox : User.default_admin.inbox
    end

    private

    def prepare_reply_params(params)
      params_with_indifferent_access = params.to_h.with_indifferent_access
      reply_to_id = params_with_indifferent_access[:reply_to_id]
      new({
        outbox: User.current.outbox,
        inbox: determine_recipient_inbox(reply_to_id),
        reply_to_id:
      }.merge(params))
    end

    def create_with_transaction(message)
      ActiveRecord::Base.transaction do
        message.save!
        yield(message) if block_given?
        message
      end
    rescue ActiveRecord::RecordInvalid => e
      message.errors.add(:base, "Error saving message: #{e.record.errors.full_messages.join(', ')}")
      message
    end

    def update_replied_message(reply_to_id, new_message_id)
      where(id: reply_to_id).update(replied: true, replied_to: new_message_id) if reply_to_id
    end
  end

  def mark_as_read
    update(read: true) unless read?
  end

  def unread?
    !read
  end

  private

  def update_inbox_and_outbox_count
    inbox.increment!(:unread_messages_count)
    outbox.increment!(:sent_messages_count)
  end

  def update_unread_count_on_read
    decrement_unread_messages_count if read?
  end

  def decrement_unread_messages_count
    inbox.decrement!(:unread_messages_count)
  end

  def decrement_unread_count_if_necessary
    decrement_unread_messages_count if unread?
  end
end

# == Schema Information
#
# Table name: messages
#
#  id              :integer          not null, primary key
#  body            :text
#  read            :boolean          default(FALSE), not null
#  replied         :boolean          default(FALSE)
#  replied_to      :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  inbox_id        :integer
#  outbox_id       :integer
#  prescription_id :integer
#  reply_to_id     :integer
#
# Indexes
#
#  index_messages_on_inbox_id                 (inbox_id)
#  index_messages_on_inbox_id_and_created_at  (inbox_id,created_at)
#  index_messages_on_outbox_id                (outbox_id)
#  index_messages_on_prescription_id          (prescription_id)
#
# Foreign Keys
#
#  prescription_id  (prescription_id => prescriptions.id)
#

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_message, only: [:show]

  def show
    @message.mark_as_read if @message.unread?
    return unless @message.nil?

    render plain: 'Not Found', status: :not_found
  end

  def new
    @message = Message.new
    @users = User.all
  end

  def create
    @users = User.all
    # Distinguish between new message and reply
    @message = if params[:message][:reply_to_id].present?
                 Message.create_reply(message_params)
               else
                 # New message
                 Message.create_message(message_params)
               end

    if @message.persisted?
      redirect_to root_path, notice: I18n.t('messages.create.success_notice')
    else
      flash.now[:alert] = I18n.t('messages.create.error_notice', message: @message.errors.full_messages.join(', '))
      render :new
    end
  end

  def index
    @messages = [Message.first]
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:body, :reply_to_id, :inbox_id, :outbox_id)
  end
end

app/views/messages/index.html.erb
<h1 class="mb-4"><%= t('application.title') %></h1>

<div class="mb-3">
  <%= link_to t('messages.index.new'), new_message_path %><br/>
  <% if User.default_doctor %>
    <%= link_to t('messages.index.doctor_inbox'), inbox_path(id: User.default_doctor) %><br/>
  <% end %>
  <% if User.current %>
    <%= link_to t('messages.index.patient_dashboard'), patient_dashboard_path(patient_id: User.current) %><br/>
  <% end %>
  <% if User.default_admin %>
    <%= link_to t('messages.index.admin_inbox'), inbox_path(id: User.default_admin) %><br/>
  <% end %>
</div>

app/views/messages/new.html.erb
<h1><%= t('messages.new.title') %></h1>
<%= form_with(model: @message, url: messages_path, method: :post, local: true) do |form| %>
  <% unless params[:original_message_id] %>
    <div class="form-group">
      <%= form.label :outbox_id, t('user.role.sender') %>
      
      <%= form.select :outbox_id, options_for_select(@users.map { |user| [user.sender_name, user.outbox.id] }, selected: @message.outbox_id), { prompt: 'Select Sender' }, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :inbox_id, t('user.role.receiver') %>
      <%= form.select :inbox_id, options_for_select(@users.map { |user| [user.recipient_name, user.inbox.id] }, selected: @message.inbox_id), { prompt: 'Select Recipient' }, class: 'form-control' %>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :body, t('messages.new.body') %>
    <%= form.text_area :body, 
                        class: "form-control", 
                        rows: 5, 
                        placeholder: t('messages.new.placeholder'), 
                        maxlength: 500 %>
    <small class="form-text text-muted">
      <%= t('messages.new.max_allowed_chars') %>
    </small>
  </div>
  <% if params[:original_message_id].present? %>
    <%= form.hidden_field :reply_to_id, value: params[:original_message_id] %>
  <% end %>
  <div class="form-group">
    <%= form.submit t('messages.new.send'), class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to t('messages.new.back'), root_path, class: "btn btn-secondary mt-3" %>

app/views/messages/show.html.erb
<h1><%= t('messages.index.view')%></h1>

<p><strong><%= t('messages.index.from')%>:</strong> <%= @message.outbox&.user&.full_name %></p>
<p><strong><%= t('messages.index.to')%>:</strong> <%= @message.inbox.user.full_name %></p>
<p><strong><%= t('messages.index.body')%>:</strong> <%= @message.body %></p>
<p><strong><%= t('messages.index.sent_at')%>:</strong> <%= @message.created_at %></p>

<%= link_to t('messages.show.back'), inbox_path(id: @message.inbox.user_id, last_message_id: @message.id + 1)%>