config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'messages#index'

  resources :messages, only: %i[create show new index]
  resources :inboxes, only: [:show]

  resources :prescriptions, only: %i[show create new index]

  resources :patients, only: [] do
    get :dashboard

    member do
      post :lost_script
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

class PatientsController < ApplicationController
  def dashboard
    @prescriptions = Prescription.where(patient: User.current)
  end

  def lost_script
    prescription = Prescription.find(params[:prescription_id])

    # Enqueue the job to handle the request
    LostScriptRequestJob.perform_later(prescription.id)

    # Redirect with a message indicating that the request has been submitted
    redirect_to patient_dashboard_path(prescription.patient.id),
                notice: I18n.t('user.patient.lost_script.dashboard_prescription_status')
  end
end

app/views/patients/dashboard.html.erb
<div class="mb-3">
  <% if User.current %>
    <%= link_to t('messages.index.patient_inbox'), inbox_path(id: User.current), class: 'btn btn-info' %>
  <% end %>
</div>
<h2><%= t('user.prescription.dashboard')%></h2>

<% if @prescriptions.empty? %>
  <%= t('messages.no_records') %>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th><%= t('user.role.doctor')%></th>
        <th><%= t('user.prescription.medication') %></th>
        <th><%= t('user.prescription.dosage') %></th>
        <th><%= t('user.prescription.issued_at') %></th>
        <th><%= t('user.prescription.valid_until') %></th>
        <th><%= t('user.prescription.actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @prescriptions.each do |prescription| %>
        <tr>
          <td><%= prescription.doctor.full_name %></td>
          <td><%= prescription.medication %></td>
          <td><%= prescription.dosage %></td>
          <td><%= format_date(prescription.issued_at) %></td>
          <td><%= format_date(prescription.valid_until) %></td>
          <td>
            <%= link_to t('messages.index.view'), prescription_path(id: prescription.id), class: "btn btn-info" %>
            <%= render_prescription_action(prescription) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>