config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'messages#index'

  resources :messages, only: %i[create show new index]
  resources :inboxes, only: [:show]

  resources :prescriptions, only: %i[show create new index]

  resources :patients, only: [] do
    get :dashboard

    member do
      post :lost_script
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/inbox.rb
# frozen_string_literal: true

class Inbox < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :nullify

  after_initialize :set_default_values

  private

  def set_default_values
    self.unread_messages_count ||= 0
  end
end

# == Schema Information
#
# Table name: inboxes
#
#  id                    :integer          not null, primary key
#  unread_messages_count :integer          default(0)
#  user_id               :integer
#
# Indexes
#
#  index_inboxes_on_unread_messages_count  (unread_messages_count)
#  index_inboxes_on_user_id                (user_id)
#

app/controllers/inboxes_controller.rb
# frozen_string_literal: true

class InboxesController < ApplicationController
  def show
    @inbox = Inbox.find_by(user_id: params[:id])
    @messages = Message.select(:id, :body, :outbox_id, :created_at, :read, :replied)
                       .includes(:outbox)
                       .where(inbox: @inbox)
                       .order(created_at: :desc)
                       .page(params[:page])
                       .per(50)
  end
end

app/views/inboxes/show.html.erb
<% if @inbox.user.is_doctor? %>
  <%= link_to t('user.prescription.new'), new_prescription_path, class: 'btn btn-info' %>
  <%= link_to t('user.prescription.list'), prescriptions_path, class: 'btn btn-info' %>
  <p/>
<% end %>
  <div><%= @inbox.user.recipient_name %> Inbox</div>
  <br/>
<% if @inbox.user.is_doctor? %>
  <div class="alert alert-info">
    <%= t('messages.inbox_unread_count', count: @inbox.unread_messages_count) %>
  </div>
<% end %>
<% if @messages.empty? %>
  <%= t('messages.no_records') %>
<% else %>
  <% cache @messages do %>
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col"><%= t('messages.index.from')%></th>
          <th scope="col"><%= t('messages.index.body')%></th>
          <th scope="col"><%= t('messages.index.sent_at')%></th>
          <th scope="col"><%= t('messages.index.read')%></th>
          <th scope="col"><%= t('messages.index.actions')%></th>
        </tr>
      </thead>
      <tbody>
        <% @messages.each_with_index do |message, index| %>
          <tr>
            <td><%= message.outbox&.user&.sender_name %></td>
            <td><%= truncate(message.body, length: 50) %></td>
            <td><%= message.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
            <td><%= message.read ? t('messages.read_yes') : t('messages.read_no') %></td>
            <td>
              <%= link_to t('messages.index.view'), message_path(message), class: message.read ? 'btn btn-light btn-sm' : 'btn btn-info btn-sm' %>
              <% if @inbox.user.is_patient? %>
                <% reply_status = message.replied? ? t('messages.show.replied') : t('messages.show.reply')%>
                <%= link_to reply_status, new_message_path(original_message_id: message.id), class: 'btn btn-warning btn-sm' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

<div class="pagination">
  <%= paginate @messages %>
</div>